# Generated by Django 3.1.5 on 2021-02-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210206_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
